name: paper-encrypt
base: core20
version: '1.0'
summary: "Encrypt and decrypt files with QR code support"
description: |
  A CLI tool to encrypt and decrypt files using AES encryption and
  embed or extract the data through QR codes.

grade: stable
confinement: strict

apps:
  paper-encrypt:
    command: bin/paper-encrypt
    plugs:
      - home
      - network

parts:
  paper-encrypt:
    plugin: python
    source: .
    python-packages:
      - pycryptodome
      - qrcode
      - fpdf
      - opencv-python
    stage-packages:
      - python3
      - python3-pip
      - libsm6
      - libxrender1
      - libfontconfig1
